import { PetDefinition } from '../core/pets/PetTypes';

export const PETS_CATALOG: Record<string, PetDefinition> = {
  pet_ignis_drake: {
    id: 'pet_ignis_drake',
    nameKey: 'pet.ignis.name',
    descKey: 'pet.ignis.desc',
    defaultName: 'Ignis the Ember Drake',
    defaultDesc: 'A fiery dragon companion born from the volcanic heart of the realm.',
    element: 'fire',
    preferredClass: 'mage',
    synergyTags: ['mage', 'pyromancy', 'elemental'],
    synergyDescKey: 'pet.ignis.synergy',
    defaultSynergyDesc: 'Mage Resonance: +15% Spell Attack & +25% Pet Combat Damage',
    synergyModifiers: [
      { id: 'syn_ignis_atk', target: 'attack', type: 'percent_add', value: 0.15 },
      { id: 'syn_ignis_pet_dmg', target: 'petDamage', type: 'percent_add', value: 0.25 },
    ],
    themeColor: '#ef4444',
    accentColor: '#f87171',
    evolutions: {
      1: {
        stage: 1,
        nameKey: 'pet.ignis.stage1.name',
        defaultName: 'Ember Hatchling',
        minLevel: 1,
        soulCost: 0,
        goldCost: 0,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#ef4444" stroke-width="2"><path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"/></svg>`,
        modifiers: [
          { id: 'pet_ignis_s1_atk', target: 'attack', type: 'percent_add', value: 0.10 },
        ],
        combatAction: {
          id: 'act_ember_breath_1',
          nameKey: 'pet.ignis.act1.name',
          descKey: 'pet.ignis.act1.desc',
          defaultName: 'Ember Breath',
          defaultDesc: 'Breathes sparks, dealing 25% pet damage every 4 seconds.',
          intervalSeconds: 4,
          damageMultiplier: 0.25,
        },
      },
      2: {
        stage: 2,
        nameKey: 'pet.ignis.stage2.name',
        defaultName: 'Flame Wyvern',
        minLevel: 10,
        soulCost: 25,
        goldCost: 15000,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#ef4444" stroke-width="2"><path d="M12 2c2 4 4 6 7 8-3 2-4 5-4 9-2-3-4-4-7-4s-5 1-7 4c0-4-1-7-4-9 3-2 5-4 7-8 2 2 4 2 8 0z"/></svg>`,
        modifiers: [
          { id: 'pet_ignis_s2_atk', target: 'attack', type: 'percent_add', value: 0.25 },
          { id: 'pet_ignis_s2_boss', target: 'bossDamage', type: 'percent_add', value: 0.15 },
        ],
        combatAction: {
          id: 'act_flame_burst_2',
          nameKey: 'pet.ignis.act2.name',
          descKey: 'pet.ignis.act2.desc',
          defaultName: 'Flame Tempest',
          defaultDesc: 'Scorches enemies with 60% pet damage and inflicts Burn debuff.',
          intervalSeconds: 3.5,
          damageMultiplier: 0.60,
          debuffType: 'burn',
          debuffDurationSeconds: 4,
          debuffValue: 0.15,
        },
      },
      3: {
        stage: 3,
        nameKey: 'pet.ignis.stage3.name',
        defaultName: 'Infernal Solar Sovereign',
        minLevel: 25,
        soulCost: 80,
        goldCost: 75000,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#ef4444" stroke-width="2"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/></svg>`,
        modifiers: [
          { id: 'pet_ignis_s3_atk', target: 'attack', type: 'percent_add', value: 0.50 },
          { id: 'pet_ignis_s3_boss', target: 'bossDamage', type: 'percent_add', value: 0.35 },
          { id: 'pet_ignis_s3_pwr', target: 'powerMultiplier', type: 'percent_add', value: 0.25 },
        ],
        combatAction: {
          id: 'act_solar_eruption_3',
          nameKey: 'pet.ignis.act3.name',
          descKey: 'pet.ignis.act3.desc',
          defaultName: 'Solar Cataclysm',
          defaultDesc: 'Unleashes stellar inferno dealing 150% pet damage and +30% Burn vulnerability.',
          intervalSeconds: 3.0,
          damageMultiplier: 1.50,
          debuffType: 'burn',
          debuffDurationSeconds: 5,
          debuffValue: 0.30,
        },
      },
    },
  },

  pet_fenrir_wolf: {
    id: 'pet_fenrir_wolf',
    nameKey: 'pet.fenrir.name',
    descKey: 'pet.fenrir.desc',
    defaultName: 'Fenrir the Frost Wolf',
    defaultDesc: 'A loyal lupine spirit harnessing the chill of northern blizzards.',
    element: 'water',
    preferredClass: 'assassin',
    synergyTags: ['assassin', 'crit', 'frost'],
    synergyDescKey: 'pet.fenrir.synergy',
    defaultSynergyDesc: 'Shadow Resonance: +8% Crit Chance & +25% Crit Damage',
    synergyModifiers: [
      { id: 'syn_fenrir_crit_ch', target: 'critChance', type: 'percent_add', value: 0.08 },
      { id: 'syn_fenrir_crit_dmg', target: 'critDamage', type: 'percent_add', value: 0.25 },
    ],
    themeColor: '#38bdf8',
    accentColor: '#7dd3fc',
    evolutions: {
      1: {
        stage: 1,
        nameKey: 'pet.fenrir.stage1.name',
        defaultName: 'Frost Pup',
        minLevel: 1,
        soulCost: 0,
        goldCost: 0,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#38bdf8" stroke-width="2"><path d="M12 2l3 6 6 1-4.5 4.5L18 20l-6-3.5L6 20l1.5-6.5L3 9l6-1z"/></svg>`,
        modifiers: [
          { id: 'pet_fenrir_s1_crit', target: 'critChance', type: 'percent_add', value: 0.05 },
        ],
        combatAction: {
          id: 'act_frost_bite_1',
          nameKey: 'pet.fenrir.act1.name',
          descKey: 'pet.fenrir.act1.desc',
          defaultName: 'Frost Bite',
          defaultDesc: 'Chills targets, dealing 30% pet damage every 4 seconds.',
          intervalSeconds: 4,
          damageMultiplier: 0.30,
        },
      },
      2: {
        stage: 2,
        nameKey: 'pet.fenrir.stage2.name',
        defaultName: 'Glacial Stalker',
        minLevel: 10,
        soulCost: 25,
        goldCost: 15000,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#38bdf8" stroke-width="2"><path d="M12 2v20M2 12h20M4.93 4.93l14.14 14.14M19.07 4.93L4.93 19.07"/></svg>`,
        modifiers: [
          { id: 'pet_fenrir_s2_crit', target: 'critChance', type: 'percent_add', value: 0.10 },
          { id: 'pet_fenrir_s2_crit_dmg', target: 'critDamage', type: 'percent_add', value: 0.25 },
        ],
        combatAction: {
          id: 'act_blizzard_howl_2',
          nameKey: 'pet.fenrir.act2.name',
          descKey: 'pet.fenrir.act2.desc',
          defaultName: 'Blizzard Howl',
          defaultDesc: 'Slows enemies with icy winds and deals 70% pet damage.',
          intervalSeconds: 3.5,
          damageMultiplier: 0.70,
          debuffType: 'slow',
          debuffDurationSeconds: 4,
          debuffValue: 0.20,
        },
      },
      3: {
        stage: 3,
        nameKey: 'pet.fenrir.stage3.name',
        defaultName: 'Abyssal Frostfang Sovereign',
        minLevel: 25,
        soulCost: 80,
        goldCost: 75000,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#38bdf8" stroke-width="2"><path d="M12 3v18M3 12h18M6 6l12 12M18 6L6 18M12 8l4 4-4 4-4-4z"/></svg>`,
        modifiers: [
          { id: 'pet_fenrir_s3_crit', target: 'critChance', type: 'percent_add', value: 0.18 },
          { id: 'pet_fenrir_s3_crit_dmg', target: 'critDamage', type: 'percent_add', value: 0.50 },
          { id: 'pet_fenrir_s3_elite', target: 'eliteDamage', type: 'percent_add', value: 0.30 },
        ],
        combatAction: {
          id: 'act_glacial_fang_3',
          nameKey: 'pet.fenrir.act3.name',
          descKey: 'pet.fenrir.act3.desc',
          defaultName: 'Absolute Zero Rend',
          defaultDesc: 'Freezes target dealing 160% pet damage and applies Vulnerability.',
          intervalSeconds: 3.0,
          damageMultiplier: 1.60,
          debuffType: 'vulnerability',
          debuffDurationSeconds: 5,
          debuffValue: 0.35,
        },
      },
    },
  },

  pet_sylph_sprite: {
    id: 'pet_sylph_sprite',
    nameKey: 'pet.sylph.name',
    descKey: 'pet.sylph.desc',
    defaultName: 'Sylph the Wind Sprite',
    defaultDesc: 'A swift elemental fairy that accelerates combat cadence and loot discovery.',
    element: 'wind',
    preferredClass: 'archer',
    synergyTags: ['archer', 'speed', 'loot'],
    synergyDescKey: 'pet.sylph.synergy',
    defaultSynergyDesc: 'Gale Resonance: +20% Attack Speed & +25% Loot Chance',
    synergyModifiers: [
      { id: 'syn_sylph_spd', target: 'attackSpeed', type: 'percent_add', value: 0.20 },
      { id: 'syn_sylph_loot', target: 'lootChance', type: 'percent_add', value: 0.25 },
    ],
    themeColor: '#10b981',
    accentColor: '#34d399',
    evolutions: {
      1: {
        stage: 1,
        nameKey: 'pet.sylph.stage1.name',
        defaultName: 'Breeze Sprite',
        minLevel: 1,
        soulCost: 0,
        goldCost: 0,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="2"><path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2M9.6 4.6A2 2 0 1 1 11 8H2M12.6 19.4A2 2 0 1 0 14 16H2"/></svg>`,
        modifiers: [
          { id: 'pet_sylph_s1_spd', target: 'attackSpeed', type: 'percent_add', value: 0.10 },
        ],
        combatAction: {
          id: 'act_zephyr_gust_1',
          nameKey: 'pet.sylph.act1.name',
          descKey: 'pet.sylph.act1.desc',
          defaultName: 'Zephyr Gust',
          defaultDesc: 'Swirls wind slicing enemies for 25% pet damage every 3 seconds.',
          intervalSeconds: 3.0,
          damageMultiplier: 0.25,
        },
      },
      2: {
        stage: 2,
        nameKey: 'pet.sylph.stage2.name',
        defaultName: 'Gale Fairy',
        minLevel: 10,
        soulCost: 25,
        goldCost: 15000,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="2"><path d="M9.59 4.59A2 2 0 1 1 11 8H2m10.59 11.41A2 2 0 1 0 14 16H2m15.73-8.27A2.5 2.5 0 1 1 19.5 12H2"/></svg>`,
        modifiers: [
          { id: 'pet_sylph_s2_spd', target: 'attackSpeed', type: 'percent_add', value: 0.25 },
          { id: 'pet_sylph_s2_loot', target: 'lootChance', type: 'percent_add', value: 0.15 },
        ],
        combatAction: {
          id: 'act_cyclone_2',
          nameKey: 'pet.sylph.act2.name',
          descKey: 'pet.sylph.act2.desc',
          defaultName: 'Aero Cyclone',
          defaultDesc: 'Whirlwind deals 60% pet damage and accelerates hero attack speed.',
          intervalSeconds: 2.8,
          damageMultiplier: 0.60,
        },
      },
      3: {
        stage: 3,
        nameKey: 'pet.sylph.stage3.name',
        defaultName: 'Tempest Empress Sylph',
        minLevel: 25,
        soulCost: 80,
        goldCost: 75000,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="2"><path d="M12 2l4 8-4 12-4-12zM2 12l8-4 12 4-12 4z"/></svg>`,
        modifiers: [
          { id: 'pet_sylph_s3_spd', target: 'attackSpeed', type: 'percent_add', value: 0.50 },
          { id: 'pet_sylph_s3_loot', target: 'lootChance', type: 'percent_add', value: 0.30 },
          { id: 'pet_sylph_s3_gold', target: 'goldMultiplier', type: 'percent_add', value: 0.20 },
        ],
        combatAction: {
          id: 'act_hurricane_sovereign_3',
          nameKey: 'pet.sylph.act3.name',
          descKey: 'pet.sylph.act3.desc',
          defaultName: 'Hurricane Sovereign',
          defaultDesc: 'Summons raging tempest dealing 140% pet damage.',
          intervalSeconds: 2.5,
          damageMultiplier: 1.40,
        },
      },
    },
  },

  pet_aegis_golem: {
    id: 'pet_aegis_golem',
    nameKey: 'pet.aegis.name',
    descKey: 'pet.aegis.desc',
    defaultName: 'Aegis the Stone Golem',
    defaultDesc: 'An impenetrable earthen defender constructed from primordial bedrock.',
    element: 'earth',
    preferredClass: 'swordsman',
    synergyTags: ['swordsman', 'power', 'defense'],
    synergyDescKey: 'pet.aegis.synergy',
    defaultSynergyDesc: 'Titan Resonance: +25% Power Multiplier & +30% Settlement Defense',
    synergyModifiers: [
      { id: 'syn_aegis_pwr', target: 'powerMultiplier', type: 'percent_add', value: 0.25 },
      { id: 'syn_aegis_def', target: 'settlementDefense', type: 'percent_add', value: 0.30 },
    ],
    themeColor: '#eab308',
    accentColor: '#fde047',
    evolutions: {
      1: {
        stage: 1,
        nameKey: 'pet.aegis.stage1.name',
        defaultName: 'Stone Pebble',
        minLevel: 1,
        soulCost: 0,
        goldCost: 0,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#eab308" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/></svg>`,
        modifiers: [
          { id: 'pet_aegis_s1_pwr', target: 'powerMultiplier', type: 'percent_add', value: 0.15 },
        ],
        combatAction: {
          id: 'act_rock_toss_1',
          nameKey: 'pet.aegis.act1.name',
          descKey: 'pet.aegis.act1.desc',
          defaultName: 'Rock Toss',
          defaultDesc: 'Hurls stone, dealing 30% pet damage every 4.5 seconds.',
          intervalSeconds: 4.5,
          damageMultiplier: 0.30,
        },
      },
      2: {
        stage: 2,
        nameKey: 'pet.aegis.stage2.name',
        defaultName: 'Granite Guardian',
        minLevel: 10,
        soulCost: 25,
        goldCost: 15000,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#eab308" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
        modifiers: [
          { id: 'pet_aegis_s2_pwr', target: 'powerMultiplier', type: 'percent_add', value: 0.30 },
          { id: 'pet_aegis_s2_def', target: 'settlementDefense', type: 'percent_add', value: 0.20 },
        ],
        combatAction: {
          id: 'act_earthquake_slam_2',
          nameKey: 'pet.aegis.act2.name',
          descKey: 'pet.aegis.act2.desc',
          defaultName: 'Earthquake Slam',
          defaultDesc: 'Slams ground dealing 75% pet damage and shreds enemy armor.',
          intervalSeconds: 4.0,
          damageMultiplier: 0.75,
          debuffType: 'armor_shred',
          debuffDurationSeconds: 4,
          debuffValue: 0.20,
        },
      },
      3: {
        stage: 3,
        nameKey: 'pet.aegis.stage3.name',
        defaultName: 'Primordial Titan Golem',
        minLevel: 25,
        soulCost: 80,
        goldCost: 75000,
        iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#eab308" stroke-width="2"><polygon points="12 2 2 7 12 12 22 7 12 2"/><polygon points="2 17 12 22 22 17"/><polygon points="2 12 12 17 22 12"/></svg>`,
        modifiers: [
          { id: 'pet_aegis_s3_pwr', target: 'powerMultiplier', type: 'percent_add', value: 0.65 },
          { id: 'pet_aegis_s3_boss', target: 'bossDamage', type: 'percent_add', value: 0.30 },
          { id: 'pet_aegis_s3_def', target: 'settlementDefense', type: 'percent_add', value: 0.40 },
        ],
        combatAction: {
          id: 'act_titan_avalanche_3',
          nameKey: 'pet.aegis.act3.name',
          descKey: 'pet.aegis.act3.desc',
          defaultName: 'Titan Avalanche',
          defaultDesc: 'Crushes enemies dealing 170% pet damage and shreds 35% armor.',
          intervalSeconds: 3.5,
          damageMultiplier: 1.70,
          debuffType: 'armor_shred',
          debuffDurationSeconds: 6,
          debuffValue: 0.35,
        },
      },
    },
  },
};

export function getPetDefinition(id: string): PetDefinition | undefined {
  return PETS_CATALOG[id];
}

export function getAllPets(): PetDefinition[] {
  return Object.values(PETS_CATALOG);
}

export function getXpRequiredForLevel(level: number): number {
  return Math.floor(100 * Math.pow(1.22, level - 1));
}
