import { CampaignEnemy } from './campaignTypes';

export const CAMPAIGN_ENEMIES: Record<string, CampaignEnemy> = {
  // World 1 - Whispering Forest
  forest_goblin: {
    id: 'forest_goblin',
    nameKey: 'enemy_forest_goblin',
    defaultName: 'Goblin Scout',
    archetype: 'melee',
    baseHpMultiplier: 0.9,
    rewardMultiplier: 1.0,
    spriteId: 'enemy_goblin',
  },
  dire_wolf: {
    id: 'dire_wolf',
    nameKey: 'enemy_dire_wolf',
    defaultName: 'Thorn Wolf',
    archetype: 'melee',
    baseHpMultiplier: 1.0,
    rewardMultiplier: 1.1,
    spriteId: 'enemy_wolf',
  },
  corrupted_treant: {
    id: 'corrupted_treant',
    nameKey: 'enemy_corrupted_treant',
    defaultName: 'Mossback Treant',
    archetype: 'tank',
    baseHpMultiplier: 1.3,
    rewardMultiplier: 1.3,
    spriteId: 'enemy_treant',
  },
  forest_spirit: {
    id: 'forest_spirit',
    nameKey: 'enemy_forest_spirit',
    defaultName: 'Whisper Sprite',
    archetype: 'magic',
    baseHpMultiplier: 0.85,
    rewardMultiplier: 1.2,
    spriteId: 'enemy_sprite',
  },
  forest_alpha: {
    id: 'forest_alpha',
    nameKey: 'enemy_forest_alpha',
    defaultName: 'Thorn Alpha',
    archetype: 'elite',
    baseHpMultiplier: 1.8,
    rewardMultiplier: 2.0,
    spriteId: 'enemy_alpha_wolf',
  },

  // World 2 - Thorncourt Marches
  rogue_ninja: {
    id: 'rogue_ninja',
    nameKey: 'enemy_rogue_ninja',
    defaultName: 'Thorncourt Skirmisher',
    archetype: 'ranged',
    baseHpMultiplier: 0.95,
    rewardMultiplier: 1.0,
    spriteId: 'enemy_ninja',
  },
  bamboo_ronin: {
    id: 'bamboo_ronin',
    nameKey: 'enemy_bamboo_ronin',
    defaultName: 'Exiled Duelist',
    archetype: 'melee',
    baseHpMultiplier: 1.1,
    rewardMultiplier: 1.15,
    spriteId: 'enemy_ronin',
  },
  temple_guardian: {
    id: 'temple_guardian',
    nameKey: 'enemy_temple_guardian',
    defaultName: 'Stone Warden',
    archetype: 'tank',
    baseHpMultiplier: 1.4,
    rewardMultiplier: 1.35,
    spriteId: 'enemy_stone_lion',
  },
  kitsune_shade: {
    id: 'kitsune_shade',
    nameKey: 'enemy_kitsune_shade',
    defaultName: 'Gloam Fox',
    archetype: 'magic',
    baseHpMultiplier: 1.0,
    rewardMultiplier: 1.25,
    spriteId: 'enemy_kitsune',
  },
  corrupted_samurai: {
    id: 'corrupted_samurai',
    nameKey: 'enemy_corrupted_samurai',
    defaultName: 'Thorncourt Champion',
    archetype: 'elite',
    baseHpMultiplier: 2.0,
    rewardMultiplier: 2.2,
    spriteId: 'enemy_corrupted_samurai',
  },

  // World 3 - Ashen Rift
  flame_imp: {
    id: 'flame_imp',
    nameKey: 'enemy_flame_imp',
    defaultName: 'Rift Imp',
    archetype: 'ranged',
    baseHpMultiplier: 0.9,
    rewardMultiplier: 1.05,
    spriteId: 'enemy_imp',
  },
  magma_beast: {
    id: 'magma_beast',
    nameKey: 'enemy_magma_beast',
    defaultName: 'Ash Hound',
    archetype: 'melee',
    baseHpMultiplier: 1.15,
    rewardMultiplier: 1.2,
    spriteId: 'enemy_magma_hound',
  },
  obsidian_golem: {
    id: 'obsidian_golem',
    nameKey: 'enemy_obsidian_golem',
    defaultName: 'Blackglass Golem',
    archetype: 'tank',
    baseHpMultiplier: 1.5,
    rewardMultiplier: 1.4,
    spriteId: 'enemy_obsidian_golem',
  },
  infernal_sorcerer: {
    id: 'infernal_sorcerer',
    nameKey: 'enemy_infernal_sorcerer',
    defaultName: 'Cinder Hexer',
    archetype: 'magic',
    baseHpMultiplier: 1.05,
    rewardMultiplier: 1.3,
    spriteId: 'enemy_pyromancer',
  },
  abyss_executioner: {
    id: 'abyss_executioner',
    nameKey: 'enemy_abyss_executioner',
    defaultName: 'Rift Executioner',
    archetype: 'elite',
    baseHpMultiplier: 2.2,
    rewardMultiplier: 2.5,
    spriteId: 'enemy_executioner',
  },

  // World 4 - Frostspire Range
  frost_wolf: {
    id: 'frost_wolf',
    nameKey: 'enemy_frost_wolf',
    defaultName: 'Frost Warg',
    archetype: 'melee',
    baseHpMultiplier: 1.0,
    rewardMultiplier: 1.1,
    spriteId: 'enemy_frost_wolf',
  },
  ice_archer: {
    id: 'ice_archer',
    nameKey: 'enemy_ice_archer',
    defaultName: 'Icebound Hunter',
    archetype: 'ranged',
    baseHpMultiplier: 0.95,
    rewardMultiplier: 1.15,
    spriteId: 'enemy_ice_archer',
  },
  glacier_elemental: {
    id: 'glacier_elemental',
    nameKey: 'enemy_glacier_elemental',
    defaultName: 'Rime Golem',
    archetype: 'tank',
    baseHpMultiplier: 1.55,
    rewardMultiplier: 1.45,
    spriteId: 'enemy_ice_titan',
  },
  blizzard_specter: {
    id: 'blizzard_specter',
    nameKey: 'enemy_blizzard_specter',
    defaultName: 'Pale Warden',
    archetype: 'magic',
    baseHpMultiplier: 1.1,
    rewardMultiplier: 1.35,
    spriteId: 'enemy_specter',
  },
  frost_wyrm: {
    id: 'frost_wyrm',
    nameKey: 'enemy_frost_wyrm',
    defaultName: 'Frost Wyrm',
    archetype: 'elite',
    baseHpMultiplier: 2.3,
    rewardMultiplier: 2.6,
    spriteId: 'enemy_frost_wyrm',
  },

  // World 5 - Umbral Sanctum
  void_crawler: {
    id: 'void_crawler',
    nameKey: 'enemy_void_crawler',
    defaultName: 'Umbral Crawler',
    archetype: 'melee',
    baseHpMultiplier: 1.05,
    rewardMultiplier: 1.15,
    spriteId: 'enemy_void_crawler',
  },
  cosmic_ray: {
    id: 'cosmic_ray',
    nameKey: 'enemy_cosmic_ray',
    defaultName: 'Rift Weaver',
    archetype: 'ranged',
    baseHpMultiplier: 1.0,
    rewardMultiplier: 1.25,
    spriteId: 'enemy_dimensional_weaver',
  },
  astral_colossus: {
    id: 'astral_colossus',
    nameKey: 'enemy_astral_colossus',
    defaultName: 'Blackstone Colossus',
    archetype: 'tank',
    baseHpMultiplier: 1.6,
    rewardMultiplier: 1.5,
    spriteId: 'enemy_astral_colossus',
  },
  singularity_cultist: {
    id: 'singularity_cultist',
    nameKey: 'enemy_singularity_cultist',
    defaultName: 'Voidbound Prophet',
    archetype: 'magic',
    baseHpMultiplier: 1.15,
    rewardMultiplier: 1.4,
    spriteId: 'enemy_void_prophet',
  },
  void_harbinger: {
    id: 'void_harbinger',
    nameKey: 'enemy_void_harbinger',
    defaultName: 'Umbral Harbinger',
    archetype: 'elite',
    baseHpMultiplier: 2.5,
    rewardMultiplier: 3.0,
    spriteId: 'enemy_void_harbinger',
  },
};

export function getCampaignEnemyById(enemyId: string): CampaignEnemy {
  return CAMPAIGN_ENEMIES[enemyId] || CAMPAIGN_ENEMIES['forest_goblin'];
}
