import { CampaignBoss } from './campaignTypes';

export const CAMPAIGN_BOSSES: Record<string, CampaignBoss> = {
  // World 1
  boss_1_5: {
    id: 'boss_1_5',
    worldId: 1,
    stageId: '1-5',
    nameKey: 'boss_1_5_name',
    defaultName: 'Grimbark the Corrupted',
    titleKey: 'boss_1_5_title',
    defaultTitle: 'Awakened Ancient',
    baseHpMultiplier: 2.5,
    timerSeconds: 30,
    spriteId: 'boss_treant',
    specialMechanic: 'shield',
    firstClearRewards: {
      gold: 500,
      power: 800,
      crystals: 50,
      essence: 10,
    },
  },
  boss_1_10: {
    id: 'boss_1_10',
    worldId: 1,
    stageId: '1-10',
    nameKey: 'boss_1_10_name',
    defaultName: 'Demon Sovereign Malgok',
    titleKey: 'boss_1_10_title',
    defaultTitle: 'Scourge of the Whispering Forest',
    baseHpMultiplier: 4.0,
    timerSeconds: 40,
    spriteId: 'boss_forest_demon',
    specialMechanic: 'enrage',
    firstClearRewards: {
      gold: 2500,
      power: 4000,
      crystals: 150,
      essence: 30,
      souls: 5,
    },
  },

  // World 2
  boss_2_5: {
    id: 'boss_2_5',
    worldId: 2,
    stageId: '2-5',
    nameKey: 'boss_2_5_name',
    defaultName: 'Shadowblade Hanzo',
    titleKey: 'boss_2_5_title',
    defaultTitle: 'Master of Nine Shadows',
    baseHpMultiplier: 2.8,
    timerSeconds: 30,
    spriteId: 'boss_shadow_ninja',
    specialMechanic: 'shield',
    firstClearRewards: {
      gold: 15000,
      power: 25000,
      crystals: 75,
      essence: 25,
    },
  },
  boss_2_10: {
    id: 'boss_2_10',
    worldId: 2,
    stageId: '2-10',
    nameKey: 'boss_2_10_name',
    defaultName: 'Shogun Ghost Nobunaga',
    titleKey: 'boss_2_10_title',
    defaultTitle: 'Immortal Sovereign of Blades',
    baseHpMultiplier: 4.5,
    timerSeconds: 45,
    spriteId: 'boss_ghost_shogun',
    specialMechanic: 'damage_reduction',
    firstClearRewards: {
      gold: 100000,
      power: 180000,
      crystals: 250,
      essence: 60,
      souls: 15,
    },
  },

  // World 3
  boss_3_5: {
    id: 'boss_3_5',
    worldId: 3,
    stageId: '3-5',
    nameKey: 'boss_3_5_name',
    defaultName: 'Magma Core Ignis',
    titleKey: 'boss_3_5_title',
    defaultTitle: 'Living Crucible',
    baseHpMultiplier: 3.0,
    timerSeconds: 30,
    spriteId: 'boss_magma_core',
    specialMechanic: 'shield',
    firstClearRewards: {
      gold: 600000,
      power: 1200000,
      crystals: 100,
      essence: 40,
    },
  },
  boss_3_10: {
    id: 'boss_3_10',
    worldId: 3,
    stageId: '3-10',
    nameKey: 'boss_3_10_name',
    defaultName: 'Abyssal Overlord Bael',
    titleKey: 'boss_3_10_title',
    defaultTitle: 'Monarch of Eternal Flame',
    baseHpMultiplier: 5.0,
    timerSeconds: 45,
    spriteId: 'boss_infernal_lord',
    specialMechanic: 'enrage',
    firstClearRewards: {
      gold: 5000000,
      power: 10000000,
      crystals: 400,
      essence: 100,
      souls: 35,
    },
  },

  // World 4
  boss_4_5: {
    id: 'boss_4_5',
    worldId: 4,
    stageId: '4-5',
    nameKey: 'boss_4_5_name',
    defaultName: 'Frost Queen Ymir',
    titleKey: 'boss_4_5_title',
    defaultTitle: 'Goddess of Absolute Zero',
    baseHpMultiplier: 3.2,
    timerSeconds: 30,
    spriteId: 'boss_frost_queen',
    specialMechanic: 'damage_reduction',
    firstClearRewards: {
      gold: 30000000,
      power: 70000000,
      crystals: 150,
      essence: 60,
    },
  },
  boss_4_10: {
    id: 'boss_4_10',
    worldId: 4,
    stageId: '4-10',
    nameKey: 'boss_4_10_name',
    defaultName: 'Glacial Dragon Nidhogg',
    titleKey: 'boss_4_10_title',
    defaultTitle: 'Terror of the Frozen Peak',
    baseHpMultiplier: 5.5,
    timerSeconds: 50,
    spriteId: 'boss_frost_dragon',
    specialMechanic: 'shield',
    firstClearRewards: {
      gold: 250000000,
      power: 600000000,
      crystals: 600,
      essence: 150,
      souls: 75,
    },
  },

  // World 5
  boss_5_5: {
    id: 'boss_5_5',
    worldId: 5,
    stageId: '5-5',
    nameKey: 'boss_5_5_name',
    defaultName: 'Cosmic Devourer',
    titleKey: 'boss_5_5_title',
    defaultTitle: 'Eater of Realities',
    baseHpMultiplier: 3.5,
    timerSeconds: 30,
    spriteId: 'boss_void_eater',
    specialMechanic: 'enrage',
    firstClearRewards: {
      gold: 2000000000,
      power: 5000000000,
      crystals: 250,
      essence: 100,
    },
  },
  boss_5_10: {
    id: 'boss_5_10',
    worldId: 5,
    stageId: '5-10',
    nameKey: 'boss_5_10_name',
    defaultName: 'Void Supreme Sovereign',
    titleKey: 'boss_5_10_title',
    defaultTitle: 'The Infinite Zero',
    baseHpMultiplier: 6.0,
    timerSeconds: 60,
    spriteId: 'boss_void_god',
    specialMechanic: 'damage_reduction',
    firstClearRewards: {
      gold: 20000000000,
      power: 50000000000,
      crystals: 1500,
      essence: 300,
      souls: 200,
    },
  },
};

export function getCampaignBossById(bossId: string): CampaignBoss | undefined {
  return CAMPAIGN_BOSSES[bossId];
}
