import { MarketOfferDefinition } from '../core/market/MarketTypes';

export const MARKET_OFFERS: Record<string, MarketOfferDefinition> = {
  // -------------------------------------------------------------
  // 1. LEGAL / NORMAL MARKET (PHASE 103)
  // -------------------------------------------------------------
  offer_iron_ore_pack: {
    id: 'offer_iron_ore_pack',
    nameKey: 'market.iron_ore_pack.name',
    defaultName: 'Mountain Iron Ore Crate',
    descKey: 'market.iron_ore_pack.desc',
    defaultDesc: 'A bundle of 20 refined Mountain Iron Ore smelted from local quarries.',
    category: 'materials',
    price: { gold: 1000 },
    rarity: 'common',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#94a3b8" stroke-width="2"><path d="M6 3h12l4 6-10 12L2 9z"/></svg>`,
    stockMax: 5,
    isBlackMarket: false,
    reward: { type: 'material', materialId: 'material_iron_ore', count: 20 },
  },

  offer_meteorite_ore_pack: {
    id: 'offer_meteorite_ore_pack',
    nameKey: 'market.meteorite_ore_pack.name',
    defaultName: 'Celestial Meteorite Ore Pouch',
    descKey: 'market.meteorite_ore_pack.desc',
    defaultDesc: 'A cache of 5 rare celestial meteorite fragments.',
    category: 'materials',
    price: { gold: 4500 },
    rarity: 'rare',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#38bdf8" stroke-width="2"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>`,
    stockMax: 3,
    isBlackMarket: false,
    reward: { type: 'material', materialId: 'material_rare_meteorite', count: 5 },
  },

  offer_settlement_timber_shipment: {
    id: 'offer_settlement_timber_shipment',
    nameKey: 'market.timber_shipment.name',
    defaultName: 'Seasoned Timber Wagon',
    descKey: 'market.timber_shipment.desc',
    defaultDesc: '150 sturdy oak timber beams for constructing and upgrading domain plots.',
    category: 'settlement',
    price: { gold: 2000 },
    rarity: 'common',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#fb923c" stroke-width="2"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M4 4.5A2.5 2.5 0 0 1 6.5 2H20"/></svg>`,
    stockMax: 2,
    isBlackMarket: false,
    reward: { type: 'settlement_materials', settlementResources: { wood: 150 } },
  },

  offer_settlement_granite_cargo: {
    id: 'offer_settlement_granite_cargo',
    nameKey: 'market.granite_cargo.name',
    defaultName: 'Quarried Granite Slabs',
    descKey: 'market.granite_cargo.desc',
    defaultDesc: '120 reinforced stone blocks to fortify walls and raise building levels.',
    category: 'settlement',
    price: { gold: 2500 },
    rarity: 'common',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#94a3b8" stroke-width="2"><polygon points="12,2 22,8.5 22,15.5 12,22 2,15.5 2,8.5"/></svg>`,
    stockMax: 2,
    isBlackMarket: false,
    reward: { type: 'settlement_materials', settlementResources: { stone: 120 } },
  },

  offer_vanguard_sword: {
    id: 'offer_vanguard_sword',
    nameKey: 'market.vanguard_sword.name',
    defaultName: 'Caravan Guard Longsword',
    descKey: 'market.vanguard_sword.desc',
    defaultDesc: 'Direct-purchase Stage 1 Apprentice Greatsword certified by Lyanna.',
    category: 'equipment',
    price: { gold: 1800 },
    rarity: 'common',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#f59e0b" stroke-width="2"><path d="M14.5 17.5L3 6V3h3l11.5 11.5M13 19l6-6M16 16l4 4M19 21l2-2"/></svg>`,
    stockMax: 1,
    isBlackMarket: false,
    reward: { type: 'equipment', templateId: 'wpn_sword_s1' },
  },

  offer_hunter_bow: {
    id: 'offer_hunter_bow',
    nameKey: 'market.hunter_bow.name',
    defaultName: 'Caravan Scout Shortbow',
    descKey: 'market.hunter_bow.desc',
    defaultDesc: 'Light yew bow suitable for swift ranged damage.',
    category: 'equipment',
    price: { gold: 1800 },
    rarity: 'common',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#38bdf8" stroke-width="2"><path d="M12 2l8 8-8 8-8-8z"/></svg>`,
    stockMax: 1,
    isBlackMarket: false,
    reward: { type: 'equipment', templateId: 'wpn_bow_s1' },
  },

  offer_merc_boran_contract: {
    id: 'offer_merc_boran_contract',
    nameKey: 'market.merc_boran.name',
    defaultName: 'Mercenary Contract: Boran Ironshield',
    descKey: 'market.merc_boran.desc',
    defaultDesc: 'Hire veteran swordsman Boran for 30 minutes (+15% Boss Damage).',
    category: 'mercenaries',
    price: { gold: 1200 },
    rarity: 'rare',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#ef4444" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
    stockMax: 1,
    isBlackMarket: false,
    reward: { type: 'mercenary', mercId: 'merc_boran' },
  },

  offer_merc_fiona_contract: {
    id: 'offer_merc_fiona_contract',
    nameKey: 'market.merc_fiona.name',
    defaultName: 'Mercenary Contract: Lady Fiona',
    descKey: 'market.merc_fiona.desc',
    defaultDesc: 'Hire radiant cleric Lady Fiona for 45 minutes (+15% Gold Multiplier).',
    category: 'mercenaries',
    price: { gold: 1600 },
    rarity: 'rare',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#34d399" stroke-width="2"><path d="M12 2v20M2 12h20"/></svg>`,
    stockMax: 1,
    isBlackMarket: false,
    reward: { type: 'mercenary', mercId: 'merc_fiona' },
  },

  offer_title_wealthy_patron: {
    id: 'offer_title_wealthy_patron',
    nameKey: 'market.title_patron.name',
    defaultName: 'Title: Wealthy Patron',
    descKey: 'market.title_patron.desc',
    defaultDesc: 'A prestigious social title bestowed upon generous caravan patrons (+10% Gold Multiplier).',
    category: 'titles',
    price: { gold: 15000 },
    rarity: 'epic',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#f59e0b" stroke-width="2"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>`,
    stockMax: 1,
    isBlackMarket: false,
    reward: { type: 'title', titleId: 'title_baron_of_commerce' },
  },

  // -------------------------------------------------------------
  // 2. BLACK MARKET / FORBIDDEN NETWORK (PHASE 106)
  // -------------------------------------------------------------
  offer_forbidden_bloodblade: {
    id: 'offer_forbidden_bloodblade',
    nameKey: 'market.forbidden_bloodblade.name',
    defaultName: 'Cursed Bloodblade of Malice',
    descKey: 'market.forbidden_bloodblade.desc',
    defaultDesc: 'A serrated black dagger dripping with forbidden necrotic ichor.',
    category: 'black_market',
    price: { gold: 8000, karmaCost: -5 },
    rarity: 'forbidden',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#f43f5e" stroke-width="2"><path d="M12 2l4 7-4 13-4-13z"/></svg>`,
    stockMax: 1,
    isBlackMarket: true,
    tradeOffDesc: '+45% Crit DMG, +20% Execute DMG, -15% Settlement DEF, -5 Karma',
    reward: { type: 'equipment', templateId: 'wpn_dagger_s2' },
  },

  offer_forbidden_vampiric_plate: {
    id: 'offer_forbidden_vampiric_plate',
    nameKey: 'market.vampiric_plate.name',
    defaultName: 'Vampiric Nightplate',
    descKey: 'market.vampiric_plate.desc',
    defaultDesc: 'A shadowy breastplate forged in forbidden blood-furnaces.',
    category: 'black_market',
    price: { gold: 9500, karmaCost: -5 },
    rarity: 'forbidden',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#7c3aed" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
    stockMax: 1,
    isBlackMarket: true,
    tradeOffDesc: '+35% Power Multiplier, +15% Speed, -10% Offline Gain, -5 Karma',
    reward: { type: 'equipment', templateId: 'arm_plate_s2' },
  },

  offer_forbidden_soul_chalice: {
    id: 'offer_forbidden_soul_chalice',
    nameKey: 'market.soul_chalice.name',
    defaultName: 'Stolen Reincarnation Chalice',
    descKey: 'market.soul_chalice.desc',
    defaultDesc: 'Bottled essence drained from the stream of Samsara. Grants immediate cultivation souls.',
    category: 'black_market',
    price: { gold: 12000, karmaCost: -10 },
    rarity: 'forbidden',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#c084fc" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20M2 12h20"/></svg>`,
    stockMax: 2,
    isBlackMarket: true,
    tradeOffDesc: 'Instant +250 Cultivation Souls, -10 Karma',
    reward: { type: 'souls', count: 250 },
  },

  offer_smuggled_meteorite_cache: {
    id: 'offer_smuggled_meteorite_cache',
    nameKey: 'market.smuggled_meteorite.name',
    defaultName: 'Smuggled Meteorite Contraband',
    descKey: 'market.smuggled_meteorite.desc',
    defaultDesc: 'Illicit shipment of 15 Celestial Meteorite Ore with erased serial runes.',
    category: 'black_market',
    price: { gold: 10000, karmaCost: -4 },
    rarity: 'forbidden',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#38bdf8" stroke-width="2"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>`,
    stockMax: 2,
    isBlackMarket: true,
    tradeOffDesc: '15 Meteorite Ore directly into inventory, -4 Karma',
    reward: { type: 'material', materialId: 'material_rare_meteorite', count: 15 },
  },

  offer_merc_sylas_contract: {
    id: 'offer_merc_sylas_contract',
    nameKey: 'market.merc_sylas.name',
    defaultName: 'Dark Pact: Sylas the Whisper',
    descKey: 'market.merc_sylas.desc',
    defaultDesc: 'Hire rogue assassin Sylas for 30 minutes (+22% Crit Damage, +8% Speed).',
    category: 'black_market',
    price: { gold: 1500, karmaCost: -3 },
    rarity: 'forbidden',
    iconSvg: `<svg viewBox="0 0 24 24" fill="none" stroke="#f43f5e" stroke-width="2"><path d="M12 2l4 7-4 13-4-13z"/></svg>`,
    stockMax: 1,
    isBlackMarket: true,
    tradeOffDesc: '+22% Crit DMG, +8% Attack Speed, -3 Karma',
    reward: { type: 'mercenary', mercId: 'merc_sylas' },
  },
};

export function getMarketOfferDef(id: string): MarketOfferDefinition | undefined {
  return MARKET_OFFERS[id];
}

export function getAllMarketOfferDefs(): MarketOfferDefinition[] {
  return Object.values(MARKET_OFFERS);
}
